/** Theme definitions for Rigbook.
 *  Each theme maps CSS custom-property names to values.
 *  `base` is "dark" or "light" — used for map-tile selection and fallback logic.
 */

export const THEMES = {
  dark: {
    label: "Dark",
    base: "dark",
    vars: {
      "--bg": "#24252b",
      "--bg-card": "#2a2d3e",
      "--bg-input": "#5a5c6a",
      "--bg-deep": "#11111b",
      "--border": "#5a5c6a",
      "--border-input": "#6e7080",
      "--text": "#eaeaea",
      "--text-muted": "#b0b2be",
      "--text-dim": "#8a8c98",
      "--text-dimmer": "#6e7080",
      "--accent": "#00ff88",
      "--accent-hover": "#00cc6a",
      "--accent-callsign": "#ffcc00",
      "--accent-vfo": "#00ccff",
      "--vfo-bg": "#111218",
      "--vfo-border": "#555",
      "--vfo-text": "#00ccff",
      "--accent-delete": "#cc3333",
      "--accent-delete-hover": "#aa2222",
      "--accent-error": "#ff6b6b",
      "--btn-secondary": "#6e7080",
      "--btn-secondary-hover": "#5a5c6a",
      "--row-hover": "#44465a",
      "--row-editing": "#3a5a3a",
      "--bar-color": "#eaeaea",
      "--menu-bg": "#2e303a",
      "--menu-hover": "#3e404a",
    },
  },
  light: {
    label: "Light",
    base: "light",
    vars: {
      "--bg": "#e8e8ff",
      "--bg-card": "#f4f4f6",
      "--bg-input": "#ffffff",
      "--bg-deep": "#f0f0f2",
      "--border": "#c8c8d0",
      "--border-input": "#b0b0b8",
      "--text": "#1a1a2e",
      "--text-muted": "#555566",
      "--text-dim": "#777788",
      "--text-dimmer": "#999aaa",
      "--accent": "#00994d",
      "--accent-hover": "#007a3d",
      "--accent-callsign": "#b8860b",
      "--accent-vfo": "#332525",
      "--vfo-bg": "#0c1e88",
      "--vfo-border": "#0c1e88",
      "--vfo-text": "#fbfbfb",
      "--accent-delete": "#cc3333",
      "--accent-delete-hover": "#aa2222",
      "--accent-error": "#cc2222",
      "--btn-secondary": "#aaaabc",
      "--btn-secondary-hover": "#9999ab",
      "--row-hover": "#dddde4",
      "--row-editing": "#c8ecc8",
      "--bar-color": "#333344",
      "--menu-bg": "#d8d8e0",
      "--menu-hover": "#c8c8d4",
    },
  },
  amber: {
    label: "Amber CRT",
    base: "dark",
    vars: {
      "--bg": "#1a1206",
      "--bg-card": "#231a0a",
      "--bg-input": "#3a2e18",
      "--bg-deep": "#110c04",
      "--border": "#4a3a1e",
      "--border-input": "#5a4828",
      "--text": "#ffbf40",
      "--text-muted": "#cc9933",
      "--text-dim": "#997722",
      "--text-dimmer": "#775a18",
      "--accent": "#ffcc00",
      "--accent-hover": "#e6b800",
      "--accent-callsign": "#ff9900",
      "--accent-vfo": "#ffdd55",
      "--vfo-bg": "#110c04",
      "--vfo-border": "#4a3a1e",
      "--vfo-text": "#ffdd55",
      "--accent-delete": "#cc5500",
      "--accent-delete-hover": "#aa4400",
      "--accent-error": "#ff6633",
      "--btn-secondary": "#5a4828",
      "--btn-secondary-hover": "#4a3a1e",
      "--row-hover": "#2e2210",
      "--row-editing": "#3a3010",
      "--bar-color": "#ffbf40",
      "--menu-bg": "#231a0a",
      "--menu-hover": "#2e2210",
    },
  },
  "field-radio": {
    label: "Field Radio",
    base: "dark",
    vars: {
      "--bg": "#1a2018",
      "--bg-card": "#222e20",
      "--bg-input": "#3a4a38",
      "--bg-deep": "#111a10",
      "--border": "#4a5a44",
      "--border-input": "#556650",
      "--text": "#c8d8b0",
      "--text-muted": "#9aaa82",
      "--text-dim": "#788868",
      "--text-dimmer": "#5a6a4e",
      "--accent": "#88cc44",
      "--accent-hover": "#6eaa33",
      "--accent-callsign": "#ddcc55",
      "--accent-vfo": "#aade66",
      "--vfo-bg": "#111a10",
      "--vfo-border": "#4a5a44",
      "--vfo-text": "#aade66",
      "--accent-delete": "#bb4433",
      "--accent-delete-hover": "#993322",
      "--accent-error": "#dd5544",
      "--btn-secondary": "#556650",
      "--btn-secondary-hover": "#4a5a44",
      "--row-hover": "#2a3828",
      "--row-editing": "#334430",
      "--bar-color": "#c8d8b0",
      "--menu-bg": "#222e20",
      "--menu-hover": "#2a3828",
    },
  },
  nixie: {
    label: "Nixie Tube",
    base: "dark",
    vars: {
      "--bg": "#0f0a08",
      "--bg-card": "#1a1210",
      "--bg-input": "#2e2220",
      "--bg-deep": "#080504",
      "--border": "#3a2a24",
      "--border-input": "#4a3830",
      "--text": "#ff8855",
      "--text-muted": "#cc6640",
      "--text-dim": "#994d30",
      "--text-dimmer": "#773a24",
      "--accent": "#ff6633",
      "--accent-hover": "#e65528",
      "--accent-callsign": "#ffaa44",
      "--accent-vfo": "#ff7744",
      "--vfo-bg": "#080504",
      "--vfo-border": "#3a2a24",
      "--vfo-text": "#ff7744",
      "--accent-delete": "#cc2200",
      "--accent-delete-hover": "#aa1a00",
      "--accent-error": "#ff4422",
      "--btn-secondary": "#4a3830",
      "--btn-secondary-hover": "#3a2a24",
      "--row-hover": "#221816",
      "--row-editing": "#2e2018",
      "--bar-color": "#ff8855",
      "--menu-bg": "#1a1210",
      "--menu-hover": "#221816",
    },
  },
  "solarized-dark": {
    label: "Solarized Dark",
    base: "dark",
    vars: {
      "--bg": "#002b36",
      "--bg-card": "#073642",
      "--bg-input": "#1a4a55",
      "--bg-deep": "#001e26",
      "--border": "#2a6070",
      "--border-input": "#3a7080",
      "--text": "#839496",
      "--text-muted": "#657b83",
      "--text-dim": "#586e75",
      "--text-dimmer": "#4a6068",
      "--accent": "#2aa198",
      "--accent-hover": "#22887f",
      "--accent-callsign": "#b58900",
      "--accent-vfo": "#268bd2",
      "--vfo-bg": "#001e26",
      "--vfo-border": "#2a6070",
      "--vfo-text": "#268bd2",
      "--accent-delete": "#dc322f",
      "--accent-delete-hover": "#c02020",
      "--accent-error": "#dc322f",
      "--btn-secondary": "#3a7080",
      "--btn-secondary-hover": "#2a6070",
      "--row-hover": "#0a404c",
      "--row-editing": "#0a3a30",
      "--bar-color": "#839496",
      "--menu-bg": "#073642",
      "--menu-hover": "#0a404c",
    },
  },
  "solarized-light": {
    label: "Solarized Light",
    base: "light",
    vars: {
      "--bg": "#fdf6e3",
      "--bg-card": "#eee8d5",
      "--bg-input": "#ffffff",
      "--bg-deep": "#f5eed8",
      "--border": "#d3cbb7",
      "--border-input": "#c0b8a4",
      "--text": "#657b83",
      "--text-muted": "#839496",
      "--text-dim": "#93a1a1",
      "--text-dimmer": "#a8b4b4",
      "--accent": "#2aa198",
      "--accent-hover": "#22887f",
      "--accent-callsign": "#b58900",
      "--accent-vfo": "#073642",
      "--vfo-bg": "#073642",
      "--vfo-border": "#073642",
      "--vfo-text": "#eee8d5",
      "--accent-delete": "#dc322f",
      "--accent-delete-hover": "#c02020",
      "--accent-error": "#dc322f",
      "--btn-secondary": "#c0b8a4",
      "--btn-secondary-hover": "#b0a894",
      "--row-hover": "#e6dfcc",
      "--row-editing": "#d5e8c8",
      "--bar-color": "#586e75",
      "--menu-bg": "#eee8d5",
      "--menu-hover": "#e6dfcc",
    },
  },
};

export const THEME_NAMES = Object.keys(THEMES);

/** Apply a theme's CSS variables to document.documentElement. */
export function applyThemeVars(themeName) {
  const theme = THEMES[themeName] || THEMES.dark;
  const style = document.documentElement.style;
  for (const [prop, val] of Object.entries(theme.vars)) {
    style.setProperty(prop, val);
  }
}

/** Resolve a theme name from storage/system-preference, falling back to "dark"/"light". */
export function resolveDefaultTheme() {
  return window.matchMedia("(prefers-color-scheme: light)").matches ? "light" : "dark";
}
